# Generated by Django 5.2.17 on 2026-09-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=200, verbose_name='Origem')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('tipo_carga', models.CharField(choices=[('GERAL', 'Carga geral'), ('FRAGIL', 'Frágil'), ('PERECIVEL', 'Perecível'), ('PERIGOSA', 'Perigosa'), ('REFRIGERADA', 'Refrigerada')], default='GERAL', max_length=20, verbose_name='Tipo de carga')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do pedido')),
                ('data_entrega_prevista', models.DateField(verbose_name='Data prevista de entrega')),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, help_text='Usado no relatório de faturamento. Pode ficar em branco.', max_digits=10, null=True, verbose_name='Valor do frete')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
    ]
