# Generated by Django 5.2.17 on 2026-09-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('EM_ROTA', 'Em rota'), ('ENTREGUE', 'Entregue'), ('ATRASADA', 'Atrasada'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO', max_length=20, verbose_name='Status')),
                ('data_prevista', models.DateField(verbose_name='Data prevista de entrega')),
                ('hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de saída')),
                ('hora_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Horário de chegada')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='motoristas.motorista', verbose_name='Motorista')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='pedidos.pedido', verbose_name='Pedido')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
