# Generated by Django 5.2.17 on 2026-09-29 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mercadoria', models.CharField(max_length=150, verbose_name='Tipo de mercadoria')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso (kg)')),
                ('volume_m3', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Volume (m³)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carga', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
            },
        ),
    ]
