# Generated by Django 5.2.17 on 2026-09-29 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Informe a placa no formato ABC1234 ou ABC1D23 (padrão Mercosul).', regex='^[A-Z]{3}\\d[A-Z0-9]\\d{2}$')], verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('capacidade_carga_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidade de carga (kg)')),
                ('situacao', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_USO', 'Em uso'), ('MANUTENCAO', 'Em manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=20, verbose_name='Situação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
    ]
