# Generated by Django 5.2.17 on 2026-09-28 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de pessoa')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome / Razão social')),
                ('cpf_cnpj', models.CharField(help_text='Somente números. 11 dígitos para CPF ou 14 para CNPJ.', max_length=14, unique=True, verbose_name='CPF ou CNPJ')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Informe o telefone apenas com números e DDD (10 ou 11 dígitos). Ex: 11987654321', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Informe o CEP apenas com números (8 dígitos). Ex: 01310100', regex='^\\d{8}$')], verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
