# Generated by Django 5.2.17 on 2026-09-29 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o CPF apenas com números (11 dígitos).', regex='^\\d{11}$')], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Informe o telefone apenas com números e DDD (10 ou 11 dígitos).', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cnh_numero', models.CharField(max_length=11, unique=True, verbose_name='Número da CNH')),
                ('cnh_categoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, verbose_name='Categoria da CNH')),
                ('cnh_validade', models.DateField(verbose_name='Validade da CNH')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
    ]
